### ISSUE TITLE
Click & drag outside in IE triggers the clickoutside event

### ISSUE THREAD

**Issue by richsage** [cowboy/jquery-outside-events#1]
I'm using jQuery sliders in a popup dialog, with the 'ciickoutside' event bound to the dialog.  If I drag the slider handle out of the dialog's area (eg to the 'max' of a slider but slightly over the right-hand edge of the dialog) and release, IE interprets this as a click outside the dialog box area and closes the dialog accordingly.

Firefox & Chrome don't exhibit this behaviour.  I'm not sure which should be correct - I'm leaning towards the FF & Chrome behaviour being correct?

**Comment by cowboy** [comment]
Can you provide a simplified test case on http://jsfiddle.net/ for this?

**Comment by richsage** [comment]
Sure - see http://jsfiddle.net/RfWrY/4/

**Comment by cowboy** [comment]
If you take a look at http://jsfiddle.net/cowboy/RfWrY/13/ you'll see that IE handles dragging differently than other browsers. Try clicking inside an element, dragging outside, and releasing. In IE, the click event is fired (on the element the mouse is released over) while in other browsers, the click event isn't fired.

This is a low-level browser issue, and while jQuery may be able to address it, it's definitely out of the scope of this plugin.

**Comment by cowboy** [comment]
One possible high-level workaround: you could track to see if both mousedown and mouseup fire on an outside element and if so, execute your code in the mouseupoutside handler.

**Comment by richsage** [comment]
Mmm, that's a good workaround for now - thanks.  I'll raise the issue over with the jQuery guys!

**Comment by cowboy** [comment]
Here's one possible approach:

```
var downOutside;
$('#test').bind( 'mousedownoutside mouseupoutside', function( e ) {
  if ( e.type == 'mousedownoutside' ) {
    downOutside = true;
  } else if ( down ) {
    downOutside = false;
    log( 'CLOSE MODAL' );
  }
});

function log() {
    $("#log").append([].join.call(arguments, ': ') + "<br/>");
}
```

See http://jsfiddle.net/cowboy/RfWrY/15/ for testing.
