### ISSUE TITLE
Clicking on a tab the click outside is not firing

### ISSUE THREAD

**Issue by downloadkwt** [cowboy/jquery-outside-events#2]
I am having a jsp that contains a jquery tab and inside tab i am having a custom search component on clicking the component a grid will open and it will act as an overlay and i used this plugin to close the grid if the user clicks outside the grid  is working perfectly in all other element click other than jquery tab selection component.Please check and give a solution.

**Comment by cowboy** [comment]
Can you post a simplified test case to [jsfiddle.net](http://jsfiddle.net/)? Thanks!

**Comment by cowboy** [comment]
OK, I'm closing this.
